export const GET_AIRLINES_DATA = 'GET_AIRLINES_DATA';
export const GET_AIRLINES_DATA_LOADING = 'GET_AIRLINES_DATA_LOADING';
export const GET_AIRLINES_DATA_SUCCESS = 'GET_AIRLINES_DATA_SUCCESS';
export const GET_AIRLINES_DATA_ERROR = 'GET_AIRLINES_DATA_ERROR';
export const SET_CUSTOM_INPUT_VALUE = 'SET_CUSTOM_INPUT_VALUE';
